language: python

python:
  - "3.5"

before_install:
  - sudo apt-get install portaudio19-dev  # for pyaudio

install:
  - pip install pipenv
  - pipenv install
  - sudo apt install pulseaudio

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cd src
  - pipenv run python test_travis.py
  - pipenv run python fuxenpruefung.py
