language: python

python:
  - "3.5"

before_install:
  - sudo apt-get install portaudio19-dev  # for pyaudio

install:
  - pip install pipenv
  - pipenv install
  - sudo apt install pulseaudio

script:
  - cd src
  - pipenv run python test_travis.py
