language: python

python:
  - "3.5"

before_install:
  - "sudo apt-get install portaudio19-dev"  # for pyaudio

install:
  - "pip install pipenv"
  - "pipenv install"

script:
  - pipenv shell
  - cd src
  - python test_travis.py
